### setting enviroment
# `Ctrl + Shift + P`, & write `Rest Client: Switch Environment`

### vars
# @apis = http://localhost:3001/api/v1

@api = {{baseUrl}}{{port}}/api/{{version}}
@endpoint = {{api}}/products

### get products list
GET {{endpoint}} HTTP/1.1

### get products list sizes 10
GET {{endpoint}}?size=4 HTTP/1.1

### get product
GET {{endpoint}}/8d

### get filtered category by id and product by id
GET {{endpoint}}/categories/1/2 HTTP/1.1

### users list with offset and limit
GET {{endpoint}}/users?limit=2&offset=2 HTTP/1.1
### users list with error
GET {{endpoint}}/users HTTP/1.1

### create product
POST {{endpoint}} HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
  "name": "Ball",
  "price": 432,
  "image": "http://placeimg.com/640/480"
}

### partial update product with PATCH
PATCH {{endpoint}}/f5c0d64c-a39b-4555-bd77-4d074b207d14 HTTP/1.1
content-type: application/json

{
  "name": "soya"
}

### complete hole update product with PUT
PUT {{endpoint}}/465817a8-a135-4e1d-8e0f-8d094a927d7a HTTP/1.1
content-type: application/json

{
  "name": "Refined Metal Ball",
  "price": 432,
  "image": "http://placeimg.com/640/480"
}

### delete only wth id
DELETE  {{endpoint}}/465817a8-a135-4e1d-8e0f-8d094a927d7a HTTP/1.1
