@api = http://localhost:3001/api/v1

### primera ruta en la historia
GET {{api}} HTTP/1.1

### ruta de prueba 2
GET {{api}}/new HTTP/1.1

### get products list
GET {{api}}/products HTTP/1.1

### get products list sizes 10
GET {{api}}/products?size=4 HTTP/1.1

### get product
GET {{api}}/products/af550f06-c91a-43e9-b4cb-a520b592d822 HTTP/1.1

### get filtered category by id and product by id
GET {{api}}/categories/1/products/2 HTTP/1.1

### users list with offset and limit
GET {{api}}/users?limit=2&offset=2 HTTP/1.1
### users list with error
GET {{api}}/users HTTP/1.1

### create product
POST {{api}}/products HTTP/1.1
content-type: application/json

{
  "name": "Refined Metal Ball",
  "price": 432,
  "image": "http://placeimg.com/640/480"
}

### partial update product with PATCH
PATCH {{api}}/products/b49952ac-86fd-41e3-ae59-d812b0c702c0 HTTP/1.1
content-type: application/json

{
  "name": "soya"
}

### complete hole update product with PUT
PUT {{api}}/products/465817a8-a135-4e1d-8e0f-8d094a927d7a HTTP/1.1
content-type: application/json

{
  "name": "Refined Metal Ball",
  "price": 432,
  "image": "http://placeimg.com/640/480"
}

### delete only wth id
DELETE  {{api}}/products/465817a8-a135-4e1d-8e0f-8d094a927d7a HTTP/1.1
