### primera ruta en la historia
GET http://localhost:3000 HTTP/1.1

### ruta de prueba 2
GET http://localhost:3000/new HTTP/1.1

### get products list
GET http://localhost:3000/api/v1/products HTTP/1.1

### get products list sizes 10
GET http://localhost:3000/api/v1/products?size=4 HTTP/1.1

### get product
GET http://localhost:3000/api/v1/products/050e5aaf-1027-4a0b-ad0d-be94c66db8dd HTTP/1.1

### get filtered category by id and product by id
GET http://localhost:3000/api/v1/categories/1/products/2 HTTP/1.1

### users list with offset and limit
GET http://localhost:3000/api/v1/users?limit=2&offset=2 HTTP/1.1
### users list with error
GET http://localhost:3000/api/v1/users HTTP/1.1

### create product
POST http://localhost:3000/api/v1/products HTTP/1.1
content-type: application/json

{
  "name": "Refined Metal Ball",
  "price": 432,
  "image": "http://placeimg.com/640/480"
}

### partial update product with PATCH
PATCH http://localhost:3000/api/v1/products/465817a8-a135-4e1d-8e0f-8d094a927d7a HTTP/1.1
content-type: application/json

{
  "name": "soya"
}

### complete hole update product with PUT
PUT http://localhost:3000/api/v1/products/465817a8-a135-4e1d-8e0f-8d094a927d7a HTTP/1.1
content-type: application/json

{
  "name": "Refined Metal Ball",
  "price": 432,
  "image": "http://placeimg.com/640/480"
}

### delete only wth id
DELETE  http://localhost:3000/api/v1/products/1 HTTP/1.1
